name: Backup Supabase

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    container:
      image: postgres:15
    steps:
      - name: Backup database
        run: |
          TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          
          pg_dump "postgresql://postgres.fefrmoncjvfkjsmvujhc:Vohoangvinh0807@db.fefrmoncjvfkjsmvujhc.supabase.co:5432/postgres" > "backup_${TIMESTAMP}.sql"
          
          gzip "backup_${TIMESTAMP}.sql"
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ env.TIMESTAMP }}
          path: backup_*.sql.gz
          retention-days: 30
